export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ATTENDANCE_FETCH_LOADING = "ATTENDANCE_FETCH_LOADING";
export const ATTENDANCE_FETCH_SUCCESS = "ATTENDANCE_FETCH_SUCCESS";
export const ADD_STUDENT_LOADING = "ADD_STUDENT_LOADING";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADMIN_ERROR = "ADMIN_ERROR";

export const REGISTER_NUMBER_LOADING = "REGISTER_NUMBER_LOADING";
export const REGISTER_NUMBER_SUCCESS = "REGISTER_NUMBER_SUCCESS";
export const PASSWORD_LOADING = "PASSWORD_LOADING";
export const PASSWORD_SUCCESS = "PASSWORD_SUCCESS";
export const CHECK_ATTENDANCE_LOADING = "CHECK_ATTENDANCE_LOADING";
export const CHECK_ATTENDANCE_SUCCESS = "CHECK_ATTENDANCE_SUCCESS";
export const MARK_ATTENDANCE_LOADING = "MARK_ATTENDANCE_LOADING";
export const MARK_ATTENDANCE_SUCCESS = "MARK_ATTENDANCE_SUCCESS";
export const STUDENT_ERROR = "STUDENT_ERROR";
